/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/**
 * ViewDrawingTab — Full-screen 2D drawing viewer for a saved View.
 *
 * Activated when the user opens a view in a new tab from ViewsPanel.
 * Reads the generated drawing from the global drawing2D store entry
 * (generated by the always-mounted Section2DPanel pipeline).
 *
 * Provides:
 *  - Zoom to cursor (wheel), fit-to-view, zoom in/out buttons
 *  - Pan (middle-mouse-button drag or alt+left-drag)
 *  - Sync drawing settings (scale, hidden lines, projection) from the view
 *  - Toolbar: regenerate, zoom controls, export
 */

import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  ZoomIn,
  ZoomOut,
  Maximize2,
  RefreshCw,
  Loader2,
  Download,
  AlertTriangle,
} from 'lucide-react';
import { GraphicOverrideEngine, type SVGExportOptions } from '@ifc-lite/drawing-2d';
import { cn } from '@/lib/utils';
import { useViewerStore } from '@/store';
import { Drawing2DCanvas } from './Drawing2DCanvas';
import { useViewControls } from '@/hooks/useViewControls';

interface ViewDrawingTabProps {
  viewId: string;
}

export function ViewDrawingTab({ viewId }: ViewDrawingTabProps) {
  // ─── Store ──────────────────────────────────────────────────────────────────
  const view              = useViewerStore((s) => s.views.get(viewId));
  const drawing           = useViewerStore((s) => s.drawing2D);
  const status            = useViewerStore((s) => s.drawing2DStatus);
  const progress          = useViewerStore((s) => s.drawing2DProgress);
  const progressPhase     = useViewerStore((s) => s.drawing2DPhase);
  const drawingError      = useViewerStore((s) => s.drawing2DError);
  const displayOptions    = useViewerStore((s) => s.drawing2DDisplayOptions);
  const activePresetId    = useViewerStore((s) => s.activePresetId);         // dep for memo
  const customOverrideRules = useViewerStore((s) => s.customOverrideRules);  // dep for memo
  const overridesEnabled  = useViewerStore((s) => s.overridesEnabled);
  const getActiveOverrideRules = useViewerStore((s) => s.getActiveOverrideRules);
  const sectionPlane      = useViewerStore((s) => s.sectionPlane);

  // ─── Activate view on mount / viewId change ──────────────────────────────
  useEffect(() => {
    const state = useViewerStore.getState();
    const vw = state.views.get(viewId);
    if (!vw) return;

    // Sync section plane settings from the view
    state.setSectionPlaneAxis(vw.sectionAxis);
    state.setSectionPlanePosition(vw.sectionPosition);

    // Activate the section tool so the renderer cuts + Section2DPanel generates
    if (vw.sectionEnabled) {
      if (state.activeTool !== 'section') {
        // Suppress the floating panel auto-open — we're showing it in a tab
        state.setSuppressNextSection2DPanelAutoOpen(true);
      }
      state.setActiveTool('section');
    } else if (state.activeTool === 'section') {
      state.setActiveTool('select');
    }

    // Sync drawing display options from the view
    state.updateDrawing2DDisplayOptions({
      showHiddenLines: vw.includeHiddenLines,
      scale: vw.scale,
    });

    // Projection mode
    state.setProjectionMode(vw.camera.projectionMode);

    // Camera position
    if (vw.camera.capturedViewpoint) {
      state.cameraCallbacks.applyViewpoint?.(vw.camera.capturedViewpoint, true, 350);
    } else if (vw.camera.presetView) {
      state.cameraCallbacks.setPresetView?.(vw.camera.presetView);
    }

    // Ensure Section2DPanel generates (it watches drawing2DPanelVisible)
    state.setDrawing2DPanelVisible(true);
  }, [viewId]);

  // ─── Suppress floating panel while tab is open ──────────────────────────
  useEffect(() => {
    // When the tab closes / unmounts, don't force-close the floating panel
    // (user may have it open from before). Just let it be.
    return () => { /* cleanup: nothing needed */ };
  }, []);

  // ─── Override engine ─────────────────────────────────────────────────────
  const overrideEngine = useMemo(
    () => new GraphicOverrideEngine(getActiveOverrideRules()),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [getActiveOverrideRules, activePresetId, customOverrideRules],
  );

  const entityColorMap = useMemo(
    () => new Map<number, [number, number, number, number]>(),
    [],
  );

  // ─── Pan / zoom via useViewControls ──────────────────────────────────────
  const containerRef = useRef<HTMLDivElement>(null);
  const cachedSheetTransformRef = useRef<{translateX: number; translateY: number; scaleFactor: number} | null>(null);

  const { viewTransform, setViewTransform, zoomIn, zoomOut, fitToView } = useViewControls({
    drawing,
    sectionPlane,
    containerRef,
    panelVisible: true,
    status,
    sheetEnabled: false,
    activeSheet: null,
    isPinned: false,
    cachedSheetTransformRef,
  });

  // Middle-mouse / alt+left pan
  const panStartRef = useRef<{mx: number; my: number; tx: number; ty: number} | null>(null);
  const transformRef = useRef(viewTransform);
  transformRef.current = viewTransform;

  const handleMouseDown = useCallback((e: React.MouseEvent) => {
    const isMiddle = e.button === 1;
    const isAltLeft = e.button === 0 && e.altKey;
    if (!isMiddle && !isAltLeft) return;
    e.preventDefault();
    panStartRef.current = {
      mx: e.clientX, my: e.clientY,
      tx: transformRef.current.x, ty: transformRef.current.y,
    };
    const onMove = (me: MouseEvent) => {
      if (!panStartRef.current) return;
      setViewTransform((t) => ({
        ...t,
        x: panStartRef.current!.tx + (me.clientX - panStartRef.current!.mx),
        y: panStartRef.current!.ty + (me.clientY - panStartRef.current!.my),
      }));
    };
    const onUp = () => {
      panStartRef.current = null;
      document.removeEventListener('mousemove', onMove);
      document.removeEventListener('mouseup', onUp);
    };
    document.addEventListener('mousemove', onMove);
    document.addEventListener('mouseup', onUp);
  }, [setViewTransform]);

  // ─── SVG export ──────────────────────────────────────────────────────────
  const handleExport = useCallback(async () => {
    if (!drawing) return;
    const { SVGExporter } = await import('@ifc-lite/drawing-2d');
    const exporter = new SVGExporter();
    const opts: SVGExportOptions = {
      showHiddenLines: displayOptions.showHiddenLines,
      showHatching: true,
      title: view?.name,
    };
    const svg = exporter.export(drawing, opts);
    const blob = new Blob([svg], { type: 'image/svg+xml' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `${view?.name ?? 'drawing'}.svg`;
    a.click();
    URL.revokeObjectURL(url);
  }, [drawing, displayOptions.showHiddenLines, view?.name]);

  // ─── Regenerate ──────────────────────────────────────────────────────────
  const handleRegenerate = useCallback(() => {
    const state = useViewerStore.getState();
    // Re-trigger generation by toggling status
    state.setDrawing2DStatus('idle');
    state.setDrawing2DPanelVisible(true);
  }, []);

  if (!view) return null;

  const isGenerating = status === 'generating';

  // ─── Render ───────────────────────────────────────────────────────────────
  return (
    <div className="flex flex-col h-full bg-muted/10">
      {/* Toolbar */}
      <div className="flex items-center gap-1 px-3 h-9 border-b bg-background shrink-0 text-xs">
        <span className="font-medium text-muted-foreground mr-1">{view.name}</span>
        <span className="text-muted-foreground/60">1:{view.scale}</span>
        <div className="flex-1" />

        {/* Regenerate */}
        <button
          onClick={handleRegenerate}
          disabled={isGenerating}
          className="h-6 w-6 flex items-center justify-center rounded hover:bg-muted transition-colors disabled:opacity-40"
          title="Regenerate drawing"
        >
          <RefreshCw className={cn('h-3.5 w-3.5', isGenerating && 'animate-spin')} />
        </button>

        {/* Zoom controls */}
        <button onClick={zoomIn}  className="h-6 w-6 flex items-center justify-center rounded hover:bg-muted" title="Zoom in">
          <ZoomIn  className="h-3.5 w-3.5" />
        </button>
        <button onClick={zoomOut} className="h-6 w-6 flex items-center justify-center rounded hover:bg-muted" title="Zoom out">
          <ZoomOut className="h-3.5 w-3.5" />
        </button>
        <button onClick={fitToView} className="h-6 w-6 flex items-center justify-center rounded hover:bg-muted" title="Fit to view">
          <Maximize2 className="h-3.5 w-3.5" />
        </button>

        {/* Export SVG */}
        <button
          onClick={handleExport}
          disabled={!drawing}
          className="h-6 w-6 flex items-center justify-center rounded hover:bg-muted disabled:opacity-40"
          title="Export SVG"
        >
          <Download className="h-3.5 w-3.5" />
        </button>
      </div>

      {/* Canvas area */}
      <div
        ref={containerRef}
        className="flex-1 min-h-0 relative overflow-hidden select-none cursor-default"
        onMouseDown={handleMouseDown}
        onContextMenu={(e) => e.preventDefault()}
      >
        {/* Progress overlay */}
        {isGenerating && (
          <div className="absolute inset-0 z-20 flex flex-col items-center justify-center gap-3 bg-background/70 backdrop-blur-sm">
            <Loader2 className="h-8 w-8 animate-spin text-primary" />
            <p className="text-sm text-muted-foreground">{progressPhase}</p>
            <div className="w-40 h-1.5 bg-muted rounded-full overflow-hidden">
              <div className="h-full bg-primary transition-all duration-300" style={{ width: `${progress}%` }} />
            </div>
          </div>
        )}

        {/* Error state */}
        {drawingError && !drawing && !isGenerating && (
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-3">
            <AlertTriangle className="h-8 w-8 text-destructive" />
            <p className="text-sm text-destructive max-w-xs text-center">{drawingError}</p>
            <button
              onClick={handleRegenerate}
              className="text-xs px-3 py-1.5 rounded border border-border hover:bg-muted transition-colors"
            >
              Try again
            </button>
          </div>
        )}

        {/* Empty state — waiting for generation */}
        {!drawing && !isGenerating && !drawingError && (
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-2 text-muted-foreground">
            <Loader2 className="h-6 w-6 animate-spin" />
            <p className="text-sm">Waiting for drawing generation…</p>
          </div>
        )}

        {/* Drawing canvas */}
        {drawing && (
          <Drawing2DCanvas
            drawing={drawing}
            transform={viewTransform}
            showHiddenLines={displayOptions.showHiddenLines}
            overrideEngine={overrideEngine}
            overridesEnabled={overridesEnabled}
            entityColorMap={entityColorMap}
            useIfcMaterials={false}
            sectionAxis={sectionPlane.axis}
          />
        )}
      </div>
    </div>
  );
}
